In [1]:
import pandas as pd

train = pd.read_csv("../data/train.csv")
features = pd.read_csv("../data/features.csv")
stores = pd.read_csv("../data/stores.csv")

In [2]:
print("Train Shape:", train.shape)
print("Features Shape:", features.shape)
print("Stores Shape:", stores.shape)

Train Shape: (421570, 5)
Features Shape: (8190, 12)
Stores Shape: (45, 3)

In [3]:
train.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [4]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [5]:
stores.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [6]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  str
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 13.3 MB

In [7]:
features.info()

<class 'pandas.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   str
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), str(1)
memory usage: 712.0 KB

In [8]:
master_df = pd.merge(
    train,
    features,
    on=["Store", "Date", "IsHoliday"],
    how="left"
)

master_df = pd.merge(
    master_df,
    stores,
    on="Store",
    how="left"
)

In [9]:
master_df.shape

(421570, 16)

In [10]:
master_df.columns

Index(['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday', 'Temperature',
       'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4',
       'MarkDown5', 'CPI', 'Unemployment', 'Type', 'Size'],
      dtype='str')

In [11]:
master_df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,A,151315

In [12]:
master_df.isnull().sum()

Store                0
Dept                 0
Date                 0
Weekly_Sales         0
IsHoliday            0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
Type                 0
Size                 0
dtype: int64

In [13]:
master_df["Date"] = pd.to_datetime(master_df["Date"])

In [14]:
master_df["Year"] = master_df["Date"].dt.year

In [15]:
master_df["Month"] = master_df["Date"].dt.month

In [16]:
master_df["Week"] = master_df["Date"].dt.isocalendar().week

In [17]:
master_df["Quarter"] = master_df["Date"].dt.quarter

In [18]:
master_df[
    ["Date", "Year", "Month", "Week", "Quarter"]
].head()

        Date  Year  Month  Week  Quarter
0 2010-02-05  2010      2     5        1
1 2010-02-12  2010      2     6        1
2 2010-02-19  2010      2     7        1
3 2010-02-26  2010      2     8        1
4 2010-03-05  2010      3     9        1

In [19]:
master_df["Date"] = pd.to_datetime(master_df["Date"])

master_df["Year"] = master_df["Date"].dt.year
master_df["Month"] = master_df["Date"].dt.month
master_df["Week"] = master_df["Date"].dt.isocalendar().week
master_df["Quarter"] = master_df["Date"].dt.quarter

master_df[
    ["Date", "Year", "Month", "Week", "Quarter"]
].head()

        Date  Year  Month  Week  Quarter
0 2010-02-05  2010      2     5        1
1 2010-02-12  2010      2     6        1
2 2010-02-19  2010      2     7        1
3 2010-02-26  2010      2     8        1
4 2010-03-05  2010      3     9        1

In [20]:
master_df.isnull().sum().sort_values(ascending=False)

MarkDown2       310322
MarkDown4       286603
MarkDown3       284479
MarkDown1       270889
MarkDown5       270138
Date                 0
Dept                 0
Store                0
Weekly_Sales         0
Fuel_Price           0
IsHoliday            0
Temperature          0
CPI                  0
Unemployment         0
Type                 0
Size                 0
Year                 0
Month                0
Week                 0
Quarter              0
dtype: int64

In [21]:
master_df.isnull().sum().sort_values(ascending=False)

MarkDown2       310322
MarkDown4       286603
MarkDown3       284479
MarkDown1       270889
MarkDown5       270138
Date                 0
Dept                 0
Store                0
Weekly_Sales         0
Fuel_Price           0
IsHoliday            0
Temperature          0
CPI                  0
Unemployment         0
Type                 0
Size                 0
Year                 0
Month                0
Week                 0
Quarter              0
dtype: int64

In [22]:
markdown_cols = [
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5"
]

master_df[markdown_cols] = master_df[markdown_cols].fillna(0)

In [23]:
master_df.isnull().sum().sort_values(ascending=False)

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
Year            0
Month           0
Week            0
Quarter         0
dtype: int64

In [24]:
master_df["Type"].unique()

<StringArray>
['A', 'B', 'C']
Length: 3, dtype: str

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

master_df["Type"] = le.fit_transform(master_df["Type"])

print(master_df["Type"].unique())

[0 1 2]

In [26]:
feature_columns = [
    "Store",
    "Dept",
    "Temperature",
    "Fuel_Price",
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5",
    "CPI",
    "Unemployment",
    "Type",
    "Size",
    "Year",
    "Month",
    "Week",
    "Quarter"
]

X = master_df[feature_columns]

y = master_df["Weekly_Sales"]

In [27]:
print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (421570, 17)
y Shape: (421570,)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(337256, 17)
(84314, 17)
(337256,)
(84314,)

In [30]:
from xgboost import XGBRegressor

print("Creating model...")

model = XGBRegressor(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1
)

print("Starting training...")

model.fit(X_train, y_train)

print("Training completed!")

Creating model...
Starting training...
Training completed!

In [31]:
predictions = model.predict(X_test)

print(predictions[:10])

[55260.19    3447.4749  9707.877   4005.8374  3783.2659  7555.9814
  3219.1006  9946.492   7766.9907 13747.005 ]

In [32]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(
    y_test,
    predictions
)

print("MAE:", mae)

MAE: 3926.8541538086997

In [33]:
print("Average Sales:", y.mean())

Average Sales: 15981.258123467042

In [34]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": predictions
})

comparison.head(20)

      Actual     Predicted
0   50932.42  55260.191406
1    3196.12   3447.474854
2   10125.03   9707.876953
3    3311.26   4005.837402
4    6335.65   3783.265869
5    8971.23   7555.981445
6    1575.35   3219.100586
7   17308.45   9946.492188
8    5763.39   7766.990723
9   17034.57  13747.004883
10    252.00   -373.371216
11   5927.00   2736.741211
12  23193.57  27036.166016
13  16863.99  15588.957031
14   6469.61   5779.563477
15  40789.48  58261.796875
16   1996.00   2446.395508
17   1451.39   6544.605469
18    795.89   3689.610596
19  13189.29  15549.970703

In [35]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
).head(10)

         Feature  Importance
1           Dept    0.294668
12          Size    0.248414
0          Store    0.087165
6      MarkDown3    0.076365
11          Type    0.068572
9            CPI    0.051588
15          Week    0.047155
14         Month    0.041646
10  Unemployment    0.018606
13          Year    0.018555

In [36]:
# --------------Model 1 Complete --------------------

In [37]:
#---- MOdel 2 Started-------

In [38]:
df_ts = master_df.copy()

In [39]:
df_ts = df_ts.sort_values(
    ["Store", "Dept", "Date"]
)

In [40]:
df_ts["Lag_1"] = (
    df_ts
    .groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .shift(1)
)

In [41]:
df_ts[
    [
        "Store",
        "Dept",
        "Date",
        "Weekly_Sales",
        "Lag_1"
    ]
].head(10)

   Store  Dept       Date  Weekly_Sales     Lag_1
0      1     1 2010-02-05      24924.50       NaN
1      1     1 2010-02-12      46039.49  24924.50
2      1     1 2010-02-19      41595.55  46039.49
3      1     1 2010-02-26      19403.54  41595.55
4      1     1 2010-03-05      21827.90  19403.54
5      1     1 2010-03-12      21043.39  21827.90
6      1     1 2010-03-19      22136.64  21043.39
7      1     1 2010-03-26      26229.21  22136.64
8      1     1 2010-04-02      57258.43  26229.21
9      1     1 2010-04-09      42960.91  57258.43

In [42]:
df_ts["Lag_4"] = (
    df_ts
    .groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .shift(4)
)

In [43]:
df_ts["Rolling_4_Week"] = (
    df_ts
    .groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .transform(
        lambda x: x.shift(1).rolling(4).mean()
    )
)

In [44]:
df_ts = master_df.copy()

df_ts = df_ts.sort_values(
    ["Store", "Dept", "Date"]
)

In [45]:
df_ts["Lag_1"] = (
    df_ts.groupby(["Store", "Dept"])
         ["Weekly_Sales"]
         .shift(1)
)

In [46]:
df_ts["Lag_4"] = (
    df_ts.groupby(["Store", "Dept"])
         ["Weekly_Sales"]
         .shift(4)
)

In [47]:
df_ts[
    [
        "Store",
        "Dept",
        "Date",
        "Weekly_Sales",
        "Lag_1",
        "Lag_4"
    ]
].head(10)

   Store  Dept       Date  Weekly_Sales     Lag_1     Lag_4
0      1     1 2010-02-05      24924.50       NaN       NaN
1      1     1 2010-02-12      46039.49  24924.50       NaN
2      1     1 2010-02-19      41595.55  46039.49       NaN
3      1     1 2010-02-26      19403.54  41595.55       NaN
4      1     1 2010-03-05      21827.90  19403.54  24924.50
5      1     1 2010-03-12      21043.39  21827.90  46039.49
6      1     1 2010-03-19      22136.64  21043.39  41595.55
7      1     1 2010-03-26      26229.21  22136.64  19403.54
8      1     1 2010-04-02      57258.43  26229.21  21827.90
9      1     1 2010-04-09      42960.91  57258.43  21043.39

In [48]:
df_ts.columns.tolist()

['Store',
 'Dept',
 'Date',
 'Weekly_Sales',
 'IsHoliday',
 'Temperature',
 'Fuel_Price',
 'MarkDown1',
 'MarkDown2',
 'MarkDown3',
 'MarkDown4',
 'MarkDown5',
 'CPI',
 'Unemployment',
 'Type',
 'Size',
 'Year',
 'Month',
 'Week',
 'Quarter',
 'Lag_1',
 'Lag_4']

In [49]:
df_ts["Rolling_4_Week"] = (
    df_ts
    .groupby(["Store", "Dept"])["Weekly_Sales"]
    .transform(
        lambda x: x.shift(1).rolling(4).mean()
    )
)

In [50]:
df_ts[
    [
        "Weekly_Sales",
        "Lag_1",
        "Lag_4",
        "Rolling_4_Week"
    ]
].head(10)

   Weekly_Sales     Lag_1     Lag_4  Rolling_4_Week
0      24924.50       NaN       NaN             NaN
1      46039.49  24924.50       NaN             NaN
2      41595.55  46039.49       NaN             NaN
3      19403.54  41595.55       NaN             NaN
4      21827.90  19403.54  24924.50      32990.7700
5      21043.39  21827.90  46039.49      32216.6200
6      22136.64  21043.39  41595.55      25967.5950
7      26229.21  22136.64  19403.54      21102.8675
8      57258.43  26229.21  21827.90      22809.2850
9      42960.91  57258.43  21043.39      31666.9175

In [51]:
df_ts[["Lag_1", "Lag_4", "Rolling_4_Week"]].isnull().sum()

Lag_1              3331
Lag_4             13134
Rolling_4_Week    13134
dtype: int64

In [52]:
df_ts = df_ts.dropna()

In [53]:
print(df_ts.shape)

(408436, 23)

In [54]:
print(df_ts["Date"].min())
print(df_ts["Date"].max())

2010-03-05 00:00:00
2012-10-26 00:00:00

In [55]:
train_df = df_ts[df_ts["Date"] < "2012-01-01"]
test_df = df_ts[df_ts["Date"] >= "2012-01-01"]

print(train_df.shape)
print(test_df.shape)

(281140, 23)
(127296, 23)

In [56]:
feature_columns_v2 = [
    "Store",
    "Dept",
    "Temperature",
    "Fuel_Price",
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5",
    "CPI",
    "Unemployment",
    "Type",
    "Size",
    "Year",
    "Month",
    "Week",
    "Quarter",
    "Lag_1",
    "Lag_4",
    "Rolling_4_Week"
]

In [57]:
X_train = train_df[feature_columns_v2]
y_train = train_df["Weekly_Sales"]

X_test = test_df[feature_columns_v2]
y_test = test_df["Weekly_Sales"]

In [58]:
print(X_train.shape)
print(X_test.shape)

(281140, 20)
(127296, 20)

In [59]:
from xgboost import XGBRegressor

model_v2 = XGBRegressor(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.05,
    random_state=42,
    n_jobs=-1
)

model_v2.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=-1, num_parallel_tree=None, ...)

In [60]:
predictions_v2 = model_v2.predict(X_test)

In [61]:
from sklearn.metrics import mean_absolute_error

mae_v2 = mean_absolute_error(
    y_test,
    predictions_v2
)

print("V2 MAE:", mae_v2)

V2 MAE: 1507.552354279781

In [62]:
print(train_df.shape)
print(test_df.shape)

(281140, 23)
(127296, 23)

In [63]:
print("V2 MAE:", mae_v2)

V2 MAE: 1507.552354279781

In [64]:
comparison_df = pd.DataFrame({
    "Model": ["V1", "V2"],
    "MAE": [3926.85, mae_v2]
})

comparison_df

  Model          MAE
0    V1  3926.850000
1    V2  1507.552354

In [65]:
df_ts["Lag_2"] = (
    df_ts.groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .shift(2)
)

df_ts["Lag_8"] = (
    df_ts.groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .shift(8)
)

df_ts["Lag_12"] = (
    df_ts.groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .shift(12)
)

In [66]:
df_ts["Rolling_8_Week"] = (
    df_ts.groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .transform(
        lambda x: x.shift(1).rolling(8).mean()
    )
)

df_ts["Rolling_12_Week"] = (
    df_ts.groupby(["Store", "Dept"])
    ["Weekly_Sales"]
    .transform(
        lambda x: x.shift(1).rolling(12).mean()
    )
)

In [67]:
feature_columns_v3 = [
    "Store",
    "Dept",
    "Temperature",
    "Fuel_Price",
    "MarkDown1",
    "MarkDown2",
    "MarkDown3",
    "MarkDown4",
    "MarkDown5",
    "CPI",
    "Unemployment",
    "Type",
    "Size",
    "Year",
    "Month",
    "Week",
    "Quarter",
    "Lag_1",
    "Lag_2",
    "Lag_4",
    "Lag_8",
    "Lag_12",
    "Rolling_4_Week",
    "Rolling_8_Week",
    "Rolling_12_Week"
]

In [68]:
train_df = df_ts[df_ts["Date"] < "2012-01-01"]
test_df = df_ts[df_ts["Date"] >= "2012-01-01"]

X_train = train_df[feature_columns_v3]
y_train = train_df["Weekly_Sales"]

X_test = test_df[feature_columns_v3]
y_test = test_df["Weekly_Sales"]

In [69]:
from xgboost import XGBRegressor

model_v3 = XGBRegressor(
    n_estimators=500,
    max_depth=10,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

In [70]:
model_v3.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [71]:
predictions_v3 = model_v3.predict(X_test)

In [72]:
from sklearn.metrics import mean_absolute_error

mae_v3 = mean_absolute_error(
    y_test,
    predictions_v3
)

print("V3 MAE:", mae_v3)

V3 MAE: 1390.9997858056952

In [73]:
comparison_df = pd.DataFrame({
    "Model": [
        "V1 Basic",
        "V2 Forecasting",
        "V3 Advanced"
    ],
    "MAE": [
        3926.85,
        1507.55,
        mae_v3
    ]
})

comparison_df

            Model          MAE
0        V1 Basic  3926.850000
1  V2 Forecasting  1507.550000
2     V3 Advanced  1390.999786

In [74]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    model_v3,
    "../models/walmart_forecasting_v3.pkl"
)

joblib.dump(
    feature_columns_v3,
    "../models/features_v3.pkl"
)

print("Model Saved Successfully")

Model Saved Successfully

In [75]:
loaded_model = joblib.load(
    "../models/walmart_forecasting_v3.pkl"
)

loaded_features = joblib.load(
    "../models/features_v3.pkl"
)

print(type(loaded_model))
print(len(loaded_features))

<class 'xgboost.sklearn.XGBRegressor'>
25

In [76]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, predictions_v3)

print("R2 Score:", r2)

R2 Score: 0.9823216418162172

In [78]:
import os

print(os.getcwd())

d:\Project\AI-Demand-Forecasting\backend\notebooks

In [79]:
import joblib

joblib.dump(
    X_test,
    "../models/X_test.pkl"
)

joblib.dump(
    y_test,
    "../models/y_test.pkl"
)

print("Saved Successfully")

Saved Successfully